const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v).toLocaleString('en-HK',{minimumFractionDigits:2,maximumFractionDigits:2});
const cn={Dining:'餐飲',Groceries:'買餸／食品',Transport:'交通',Shopping:'購物',Subscriptions:'訂閱',Bills:'帳單',Health:'健康',Home:'家居',Entertainment:'娛樂',Travel:'旅遊',Pets:'寵物',Other:'其他'};
const types={Income:'收入',Expense:'支出',Refund:'退款',Transfer:'自己戶口互轉',CardRepayment:'還卡數'};
const date=v=>typeof v==='number'?new Date(Date.UTC(1899,11,30)+v*864e5).toISOString().slice(0,10):String(v||'').slice(0,10);
const stamp=v=>new Date(v).toLocaleString('zh-HK',{timeZone:'Asia/Hong_Kong',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
const objects=rows=>rows.slice(1).map(r=>Object.fromEntries(rows[0].map((h,i)=>[h,r[i]??'']))).filter(r=>r['Transaction ID']||r['Event ID']);
const real=r=>! /TEST-|EXAMPLE/i.test(r['Transaction ID']||r['Event ID'])&&! /TEST DATA/i.test(r.Notes||'');
const sum=(rs,type)=>rs.filter(r=>r.Type===type&&typeof r.Amount==='number').reduce((s,r)=>s+Math.abs(r.Amount),0);
let incomeHidden=true;try{incomeHidden=localStorage.getItem('ledger-hide-income')!=='false'}catch{}
let selectedDay=null,selectedMonth='';
const incomeRow=(r,event=false)=>!event?r.Type==='Income':tx.some(t=>t['Transaction ID']===r['Matched Transaction ID']&&t.Type==='Income')||/received|sent you|sent .*to your account|薪金|收入|收款|收到/i.test(String(r['Raw Text'])+' '+String(r.Notes));
function privacyUI(){$('#privacy-toggle').textContent=incomeHidden?'顯示收入':'隱藏收入';$('#privacy-toggle').setAttribute('aria-pressed',String(incomeHidden));}
$('#privacy-toggle').onclick=()=>{incomeHidden=!incomeHidden;try{localStorage.setItem('ledger-hide-income',String(incomeHidden))}catch{}privacyUI();if(data)render()};privacyUI();
let data,tx=[],events=[],page='home',filter='pending',editing=null,refreshing=false;
$('#month').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit'}).format(new Date()).replace(/^(\d{2})\/(\d{4})$/,'$2-$1');
const empty=text=>`<div class="empty">${esc(text)}</div>`;
function setPage(p){page=p;all('.page').forEach(n=>n.hidden=n.id!==p);all('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#page-title').textContent={home:'我的收支總覽',records:'每一筆，都清楚',cards:'卡與付款渠道',analysis:'了解我的消費'}[p];if(data)render()}
all('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));all('[data-go]').forEach(b=>b.onclick=()=>setPage(b.dataset.go));
function row(r,event=false){if(incomeHidden&&(event||incomeRow(r,event)))return '<div class="hidden-income">◉ '+(event?'通知內容已隱藏':'收入記錄已隱藏')+'</div>';const id=r[event?'Event ID':'Transaction ID'],merchant=r[event?'Parsed Merchant':'Clean Merchant']||'未識別商戶',a=r[event?'Parsed Amount':'Amount'];const linked=event&&r['Matched Transaction ID'];const pending=event&&!linked;const t=event?'':r.Type;const note=event?'':r['Manual Remark']||r['AI Remark'];return `<article class="record"><div class="record-top"><span class="avatar">${esc(merchant.slice(0,1))}</span><div class="record-info"><strong>${esc(merchant)}</strong><small>${esc(date(r[event?'Event Time':'Date'])||'日期待確認')} · ${esc(event?r['Source App / Sender']:cn[r.Category]||r.Category)}</small></div><div class="amount ${t==='Income'||t==='Refund'?'income':''}">${t==='Income'||t==='Refund'?'+':''}${esc(r.Currency)} ${typeof a==='number'?money(a):'待確認'}<small class="record-state ${pending?'pending':'confirmed'}"><i class="status-dot ${pending?'red':''}" aria-hidden="true"></i>${pending?'待確認':linked?'已入帳':esc(types[t]||t)}</small></div></div><div class="record-bottom"><p>${esc(event?(pending?'已保存原文，未計入收支':'來源通知已保留'):(r.Subcategory||note||'可補充商品或備註'))}</p><button data-edit="${esc(linked||id)}" data-source="${event&&!linked?'event':'transaction'}">${pending?'核實分類':'編輯'}</button></div>${event?`<details><summary>原始通知 · ${typeof r['Parser Confidence']==='number'?Math.round(r['Parser Confidence']*100)+'% 抽取信心':'未提供信心分數'}</summary><pre>${incomeHidden?'私隱模式已隱藏通知原文；顯示收入後可查看。':esc(r['Raw Text'])}</pre></details>`:''}</article>`}
function categories(rs){const cats={};rs.filter(r=>r.Type==='Expense'&&typeof r.Amount==='number').forEach(r=>cats[r.Category||'Other']=(cats[r.Category||'Other']||0)+Math.abs(r.Amount));const total=Object.values(cats).reduce((a,b)=>a+b,0);return Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,a])=>`<div class="category"><div class="category-head"><span>${esc(cn[c]||c)}<small>${Math.round(a/total*100)}%</small></span><strong>$${money(a)}</strong></div><div class="bar"><span style="width:${a/total*100}%"></span></div></div>`).join('')||empty('本月未有已核實支出。')}
function channelName(value){
 const name=String(value||'').trim();
 if(/pay\s*me/i.test(name))return 'PayMe';
 if(/\bmox\b/i.test(name))return 'Mox';
 if(/hsbc|滙豐|匯豐/i.test(name))return 'HSBC';
 if(/渣打|standard\s*chartered|sc\s*mobile|\bscb\b|cathay|國泰/i.test(name))return '渣打';
 if(/octopus|八達通/i.test(name))return '八達通';
 if(/^(?:apple\s*)?wallet$/i.test(name))return 'Apple Wallet（銀行未識別）';
 return name||'未指定渠道';
}
function paymentGroups(rows){const groups=new Map();for(const r of rows){const name=channelName(r['Payment Method']);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(r)}return [...groups.entries()]}
function render(){tx=objects(data.transactions).filter(real);events=objects(data.events).filter(real);const m=$('#month').value,monthly=tx.filter(r=>date(r.Date).startsWith(m)),hkd=monthly.filter(r=>r.Currency==='HKD');const pending=events.filter(r=>!r['Matched Transaction ID']);const income=sum(hkd,'Income'),expense=sum(hkd,'Expense'),refund=sum(hkd,'Refund');$('#income').textContent=incomeHidden?'••••':'$'+money(income);$('#expense').textContent='$'+money(expense);$('#balance').textContent=incomeHidden?'••••':'$'+money(income-expense+refund);$('#refund').textContent='退款 $'+money(refund);$('#badge').textContent=pending.length||'';$('#review-banner').classList.toggle('clear',!pending.length);$('#review-banner').innerHTML=`<span><b><i class="status-dot ${pending.length?'red':''}" aria-hidden="true"></i>${pending.length?`${pending.length} 筆通知等你核實`:'所有通知已核實'}</b><small>按一下分類、補充內容，確認後計入帳簿。</small></span><span>↗</span>`;$('#latest').innerHTML=[...monthly].sort((a,b)=>date(b.Date).localeCompare(date(a.Date))).slice(0,5).map(r=>row(r)).join('')||empty('本月未有正式交易。收到通知後可到「記錄與核實」確認。');$('#categories').innerHTML=categories(hkd);$('#category-preview').innerHTML=categories(hkd);
const query=$('#search').value.toLowerCase();let rows=filter==='pending'?pending:filter==='events'?events.filter(r=>date(r['Received At']).startsWith(m)):monthly;rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query)).sort((a,b)=>String(b['Received At']||b.Date).localeCompare(String(a['Received At']||a.Date)));$('#record-list').innerHTML=rows.map(r=>row(r,filter!=='transactions')).join('')||empty(filter==='pending'?'暫時冇待核實通知。':'冇符合條件嘅記錄。');$('#list-help').textContent=filter==='pending'?'列出所有月份未核實通知，避免漏記。請按「核實分類」確認實際用途。':filter==='events'?'本月原始通知；同一筆交易可保留多個來源。':'本月正式交易。修改商品、類別及備註會同步儲存到 Google Sheet。';
$('#card-list').innerHTML=paymentGroups(monthly).map(([name,rs])=>{
 const currencies=[...new Set(rs.map(r=>r.Currency))];
 const cards=[...new Set(rs.map(r=>String(r['Card Last4']||'')).filter(Boolean))];
 const net=currencies.map(c=>{const part=rs.filter(r=>r.Currency===c);return `<strong>${esc(c)} ${money(sum(part,'Expense')-sum(part,'Refund'))}</strong>`}).join('');
 const totals=currencies.map(c=>{const part=rs.filter(r=>r.Currency===c);return `<div class="card-totals" aria-label="${esc(c)} 收支"><div>${esc(c)} 消費<b>${money(sum(part,'Expense'))}</b></div><div>退款<b>${money(sum(part,'Refund'))}</b></div><div>收到款項<b>${incomeHidden?'••••':money(sum(part,'Income'))}</b></div><div>已記錄還款<b>${money(sum(part,'CardRepayment'))}</b></div></div>`}).join('');
 return `<article class="payment-card"><div class="plastic"><h3>${esc(name)}</h3><small>本月已記錄淨消費</small>${net}<small>${cards.length?cards.map(c=>'•••• '+esc(c)).join(' · '):'付款渠道'}</small></div>${totals}<p class="hint">${rs.length} 筆正式記錄 · 同渠道來源已合併 · 非銀行應繳結欠</p></article>`
}).join('')||empty('本月未有卡或渠道記錄。');
const days=new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate(),values=Array(days).fill(0);hkd.filter(r=>r.Type==='Expense'&&typeof r.Amount==='number').forEach(r=>{const d=Number(date(r.Date).slice(8,10));if(d>0&&d<=days)values[d-1]+=Math.abs(r.Amount)});const max=Math.max(...values,1),peak=values.indexOf(Math.max(...values))+1;
if(selectedMonth!==m){selectedDay=peak;selectedMonth=m}selectedDay=Math.min(selectedDay||peak,days);
const ranked=values.map((value,i)=>({value,day:i+1})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,3);
const chart=`<div class="chart-summary"><div>最高消費日<strong>${ranked.length?ranked[0].day+' 日 · $'+money(ranked[0].value):'尚未有消費'}</strong></div><div>有消費日數<strong>${values.filter(v=>v>0).length} 日</strong></div></div><div class="daily-interactive" aria-label="每日消費，按日期查看交易">${values.map((v,i)=>`<button class="day-button ${i+1===peak?'peak':''}" data-day="${i+1}" aria-label="${i+1} 日，支出 HKD ${money(v)}" aria-pressed="${selectedDay===i+1}"><span style="height:${v?Math.max(3,v/max*100):2}%"></span></button>`).join('')}</div><div class="chart-labels"><span>1 日</span><span>8 日</span><span>15 日</span><span>22 日</span><span>${days} 日</span></div><div class="peak-days">${ranked.map((x,i)=>`<button data-day="${x.day}">#${i+1} · ${x.day} 日 $${money(x.value)}</button>`).join('')}</div>`;
$('#home-daily').innerHTML=chart;$('#daily').innerHTML=chart;
const dayRows=hkd.filter(r=>r.Type==='Expense'&&Number(date(r.Date).slice(8,10))===selectedDay);
const dayHtml=`<div class="day-detail"><h3>${m.slice(5)} 月 ${selectedDay} 日 · HK$ ${money(values[selectedDay-1]||0)}</h3>${dayRows.map(r=>`<p><span>${esc(r['Clean Merchant'])}</span><b>$${money(r.Amount)}</b></p>`).join('')||'<p>當日未有已記錄支出。</p>'}</div>`;
$('#day-detail').innerHTML=dayHtml;$('#daily').insertAdjacentHTML('beforeend',dayHtml);
$('#foreign').textContent=monthly.some(r=>r.Currency!=='HKD')?'外幣保留原幣，未換算到 HKD 總覽；可在卡與渠道查看。':'';$('#channels').innerHTML=[...new Set(tx.map(r=>channelName(r['Payment Method'])).filter(Boolean))].map(c=>`<option value="${esc(c)}">`).join('');}
$('#month').onchange=()=>data&&render();$('#search').oninput=()=>data&&render();all('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;all('[data-filter]').forEach(n=>n.classList.toggle('active',n===b));if(data)render()});
const form=$('#edit-form');form.elements.category.innerHTML=Object.entries(cn).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
document.addEventListener('click',e=>{const d=e.target.closest('[data-day]');if(d){selectedDay=Number(d.dataset.day);render();return;}const b=e.target.closest('[data-edit]');if(!b)return;const isEvent=b.dataset.source==='event',r=(isEvent?events:tx).find(r=>r[isEvent?'Event ID':'Transaction ID']===b.dataset.edit);if(!r)return;if(incomeHidden&&incomeRow(r,isEvent))return;editing={r,isEvent};form.reset();const values={type:isEvent?'':r.Type,category:isEvent?(String(r.Notes).match(/category=([^;]+)/)?.[1]||'Other'):r.Category,amount:r[isEvent?'Parsed Amount':'Amount'],currency:r.Currency||'HKD',date:date(r[isEvent?'Event Time':'Date']),merchant:r[isEvent?'Parsed Merchant':'Clean Merchant'],payment_method:r[isEvent?'Source App / Sender':'Payment Method'],card_last4:r['Card Last4'],items:isEvent?'':r.Subcategory,remark:isEvent?'':r['Manual Remark']};for(const[k,v]of Object.entries(values))form.elements[k].value=v??'';$('#edit-title').textContent=isEvent?'核實這筆交易':'編輯交易';$('#edit-context').textContent=isEvent?'請確認係收入、支出、退款或戶口互轉。只憑轉入通知，未必知道款項用途。':'修改會同步更新統計，原始通知仍然保留。';$('#raw').textContent=incomeHidden?'私隱模式已隱藏原始資料。':isEvent?r['Raw Text']:events.filter(e=>e['Matched Transaction ID']===r['Transaction ID']).map(e=>e['Raw Text']).join('\n\n')||r['Original Merchant'];$('#save-status').textContent='';$('#editor').showModal();});
$('#close-editor').onclick=()=>$('#editor').close();
form.onsubmit=async e=>{e.preventDefault();if(!editing)return;const v=Object.fromEntries(new FormData(form));v.amount=Number(v.amount);const {r,isEvent}=editing;if(isEvent)v.event_id=r['Event ID'];else{v.transaction_id=r['Transaction ID'];v.expected_updated_at=r['Updated At'];}$('#save').disabled=true;$('#close-editor').disabled=true;$('#save-status').innerHTML='<i class="status-dot yellow" aria-hidden="true"></i>正在儲存到帳簿…';try{const res=await fetch('/api/transaction',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v),signal:AbortSignal.timeout(50000)});const result=await res.json();if(!res.ok||result.ok!==true)throw Error(result.error||'save_failed');$('#editor').close();$('#toast').hidden=false;$('#toast').textContent='✓ 已儲存到帳簿';setTimeout(()=>$('#toast').hidden=true,4500);await refresh();}catch(err){$('#save-status').textContent=err.message==='conflict'?'記錄已被更新。請關閉、更新資料後再編輯。':'未能確認儲存結果。請先更新帳簿查看，避免重複核實；你輸入嘅內容仍然保留。';}finally{$('#save').disabled=false;$('#close-editor').disabled=false;}};
$('#editor').addEventListener('cancel',e=>{if($('#save').disabled)e.preventDefault()});
async function refresh(){if(refreshing)return;refreshing=true;$('#refresh').disabled=true;$('#status').innerHTML='<i class="status-dot yellow" aria-hidden="true"></i>正在讀取 Google Sheet…';try{const r=await fetch('/api/ledger',{cache:'no-store',signal:AbortSignal.timeout(50000)});const d=await r.json();if(!r.ok||d.live!==true||d.transactions?.[0]?.[0]!=='Transaction ID'||d.events?.[0]?.[0]!=='Event ID'||!Number.isFinite(Date.parse(d.fetchedAt)))throw Error();data=d;render();$('#status').classList.remove('error');$('#status').innerHTML='<i class="status-dot" aria-hidden="true"></i>已連接 · 每 60 秒自動更新';$('#updated').textContent='成功讀取 '+stamp(d.fetchedAt)+'（香港）';}catch{$('#status').classList.add('error');$('#status').textContent=data?'暫時連線失敗，顯示上次資料。':'未能連接帳簿，請稍後更新。';}finally{refreshing=false;$('#refresh').disabled=false;}}
$('#refresh').onclick=refresh;setInterval(()=>{if(!document.hidden&&!$('#editor').open)refresh()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('#editor').open)refresh()});await refresh();
